---
- name: Add user
  ansible.builtin.user:
    name: "{{ act_runner_user }}"

- name: Create application directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ act_runner_user }}"
    group: "{{ act_runner_user }}"
    mode: 0755
  become: true
  with_items:
    - "{{ act_runner_dir }}"

- name: Download latest release
  ansible.builtin.get_url:
    url: "{{ act_runner_download_url }}"
    checksum: "{{ act_runner_download_checksum | default(omit) }}"
    dest: "{{ act_runner_dir }}/act_runner-{{ act_runner_version }}"
    owner: "{{ act_runner_user }}"
    mode: 0755
  become: true

- name: Create current symlink
  ansible.builtin.file:
    src: "{{ act_runner_dir }}/act_runner-{{ act_runner_version }}"
    dest: "{{ act_runner_dir }}/act_runner-current"
    state: "link"
  become: true
  notify:
    - Service restart

- name: decide whether config is needed
  ansible.builtin.set_fact:
    act_runner_config_needed: "{{ act_runner_cache_ip | length > 0 }}"

- name: validate options
  ansible.builtin.assert:
    that: 
      - act_runner_cache_port | length > 0
  when: act_runner_config_needed

- name: copy config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ act_runner_dir }}/config.yaml"
    owner: "{{ act_runner_user }}"
    mode: 0644
  become: true
  when: act_runner_config_needed

- name: Register runner
  ansible.builtin.command:
    chdir: "{{ act_runner_dir }}"
    cmd: "sudo -u {{act_runner_user}} {{ act_runner_dir }}/act_runner-current register {{ act_runner_config_needed | ternary('--config '+act_runner_dir+'/config.yaml','')}}--instance {{ act_runner_instance }} --token {{ act_runner_token }} --no-interactive"
    creates: "{{ act_runner_dir }}/.runner"
  when: act_runner_instance is defined and act_runner_token is defined

- name: Deploy systemd service file
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/{{ act_runner_identifier }}.service"
    mode: 0644
  become: true
  notify:
    - Service restart

- name: Service start
  ansible.builtin.systemd:
    name: "{{ act_runner_identifier }}"
    state: "started"
    enabled: true
  become: true
