---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu2204
    box: generic/ubuntu2204
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c .yamllint.yml .
  ansible-lint .
